# == CONFIG ==

# Environment parameters
environment:
  envName: "cont-obs-avoid-v0"
  numEnvs: 8
  doneType: "TF" # toThreshold
  costType: "max_ell_g"
  addObs: False
  numObstacles: 3
  randomSeed: 7
  reward: -1.0
  penalty: 1.0
  scaling: 16.0
  timeStep: 0.1
  physicstimeStep: 0.01
  maxSteps: 300


# Training scheme
training:
  warmup: true
  warmupIter: 2000
  maxUpdates: 3000000
  updateTimes: 10
  updatePeriodEps: 5.0e+5
  updatePeriodGamma: 1.0e+5
  updatePeriodLr: 5.0e+5
  memoryCapacity: 50000 
  checkPeriod: 50000
  batchSize: 256
  maxModel: 100
  tau: 0.005
  hardUpdate: 1
  softUpdate: true
  render: false
  double: true
  plotTrainValue: true
  alpha: 0.185
  policy: "Gaussian"
  targetUpdateInterval: 1
  autoAlphaTuning: true


# NN hyper-parameters
network:
  annealing: true
  criticArchitecture: [512, 512]
  actorArchitecture: [512, 512]
  learningRate: 0.001
  learningRateActor: 0.001
  learningRateDecay: 0.8
  gamma: 0.95 # 0.9999
  gammaDecay: 0.1
  eps: 0.5
  epsEnd: 0.05
  epsDecay: 0.7
  actType: "ReLU"
  numCritics: 3

# RL type
rl:
  mode: "AARA"
  terminalType: "max"

# File
file:
  showTime: true
  name: ""
  outFolder: "experiments"
  plotFigure: false
  storeFigure: true
  storeBest: false
  

# Adversary parameters
adversary:
  # for the function select_action() in DDQNSingle.py
  selectWorstQ: false
  # for the find_worst_d() function in zermelo_show.py
  findMaxQ: true
  # for the simulate_one_trajectory() function in zermelo_show.py (eval)
  simMaxQ: true
  # for the final test (of each point in the env) in sim_new_point_mass.py
  testMaxQ: true