##################################################
# Configuration file for the guidance, navigation
# and control modules running on the abv.
#################################################

Guidance:
  StateMachine:
    Rate: 10 # Hz
    WaypointTimeout: 30 # seconds - default max time to wait for arrival at a single waypoint
    WaypointTimeoutToleranceScale: 2.0 # multiplier on arrival tolerance checked when a waypoint timeout fires

Navigation:
  Interface: optitrack
  Rate: 25 # Hz
  RigidBodyName: ABV1

  Network:
    Local:
      Ip: 192.168.1.242

    Server:
      Ip: 127.0.0.1

Control:
  StateMachine:
    Rate: 10 # hz

  Arrival:
    Tolerance: [0.05, 0.05, 0.05] # [m, m, rad]
    Duration: 3 # seconds

  Gains:
    Kp: [25.0, 25.0, 5.0]
    Ki: [0, 0, 0]
    Kd: [55.0, 55.0, 15.0]

  Thrusters:
    InputDiscretization:
      On: 0.2
      Off: 0.09

    ThrusterDriver:
      Type: JETGPIO
      GPIO:
        pins: [12, 7, 8, 24, 19, 22, 15, 13]

  Dynamics:
    Mass: 12.7 # kg
    Inertia: 0.3 # kg-m^2
    ThrusterForce: 0.08 # N
    MomentArm: 0.125 # m
