##################################################
# Configuration file for the guidance, navigation
# and control modules running on the abv.
#################################################

Guidance:
  StateMachine:
    Rate: 10 # Hz

Navigation:
  Interface: simulated
  Rate: 25 # Hz
  RigidBodyName: ABV1

  Network:
    Local:
      Ip: 192.168.1.15

    Server:
      Ip: 192.168.1.152

Control:
  StateMachine:
    Rate: 10 # hz

  Arrival:
    Tolerance: [0.05, 0.05, 0.05] # [m, m, rad]
    Duration: 3 # seconds

  Gains:
    Kp: [50.0, 50.0, 25.0]
    Ki: [0.001, 0.001, 0.001]
    Kd: [315.0, 315.0, 75.0]

  Thrusters:
    InputDiscretization:
      On: 0.2
      Off: 0.09

    Allocation:
      x: [0, 0, -1, -1, 0, 0, 1, 1]
      y: [1, 1, 0, 0, -1, -1, 0, 0]
      yaw: [-1, 1, -1, 1, -1, 1, -1, 1]

    ThrusterDriver:
      Type: JETGPIO
      GPIO:
        pins: [12, 7, 8, 24, 19, 22, 15, 13]

  Dynamics:
    Mass: 12.7 # kg
    Inertia: 0.3 # kg-m^2
    ThrusterForce: 0.08 # N
    MomentArm: 0.125 # m
